#!/usr/bin/env bash

npm run build

mkdir deploy &> /dev/null
tar czf deploy/bp.tar.gz build
scp deploy/bp.tar.gz $BP_SFTP_ADDRESS:

#
ssh $BP_SSH_ADDRESS /bin/bash << EOF
tar xzf bp.tar.gz -C $BP_DIR --strip-components=1
EOF

exit $?
