name: continuous-deployment
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
        shell: bash
        env:
          DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}

      - name: Install PM2
        run: npm i pm2

      - name: Deploy
        run: pm2 deploy ecosystem.config.js production