name: continuous-deployment
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$DEPLOY_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Install PM2
        run: npm i -g pm2

      - name: Deploy
        run: pm2 deploy ecosystem.config.cjs production
        env:
          BPW_USER: ${{ vars.BPW_USER }}
          BPW_HOST: ${{ vars.BPW_HOST }}
          BPW_PATH: ${{ vars.BPW_PATH }}
